### ISSUE TITLE
Burp 2023.10.2.4: java.lang.Exception: Extension class is not a recognized type

### ISSUE THREAD

**Issue by kamalpreetSec** [silentsignal/burp-image-size#4]
I have created a helloworld extension and getting the below error when I try to load (exported runnable jar: helloworld.jar) it in Burp UI:

java.lang.Exception: Extension class is not a recognized type
	at burp.Zgbi.Zo(Unknown Source)
	at burp.Zgbi.ZQ(Unknown Source)
	at burp.Zw8a.Zl(Unknown Source)
	at burp.Zelj.ZS(Unknown Source)
	at burp.Zqu6.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

Burp 2023.10.2.4
Java : 17.0.9+11-LTS-201
My laptop has Windows 10 pro

Java class:

/*
 * Copyright (c) 2022-2023. PortSwigger Ltd. All rights reserved.
 *
 * This code may be used to extend the functionality of Burp Suite Community Edition
 * and Burp Suite Professional, provided that this usage does not violate the
 * license terms for those products.
 */

package com.burp.montoya.helloworld;

import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;
import burp.api.montoya.logging.Logging;

//Burp will auto-detect and load any class that extends BurpExtension.
public class HelloWorld implements BurpExtension
{
    @Override
    public void initialize(MontoyaApi api)
    {
        // set extension name
        api.extension().setName("Hello world extension");

        Logging logging = api.logging();

        // write a message to our output stream
        logging.logToOutput("Hello output.");

        // write a message to our error stream
        logging.logToError("Hello error.");

        // write a message to the Burp alerts tab
        logging.raiseInfoEvent("Hello info event.");
        logging.raiseDebugEvent("Hello debug event.");
        logging.raiseErrorEvent("Hello error event.");
        logging.raiseCriticalEvent("Hello critical event.");

        // throw an exception that will appear in our error stream
        throw new RuntimeException("Hello exception.");
    }
}

**Comment by kamalpreetSec** [comment]
Using Montoya API for creating this extension

**Comment by dnet** [comment]
This is the issue tracker of _a_ Burp extension, not Burp itself, please contact the developers of Burp Suite directly with such issues: https://portswigger.net/support
